owners: 
    aliases:
        - owner
    default: []
    label: Owner
    description: Always consent to any action from your owner. Owners are also asked for consent instead of you.
    emoji: ğŸ‘‘
    permission: 
        permission_ask: "{target_member}, {invoker_member} would like you to be their Owner. Do you agree?"
        permission_accept: "{target_member} is now your Owner, {invoker_member}."
        permission_deny: "Sorry {invoker_member}. {target_member} declined to become your Owner."
    
allowed: 
    aliases:
        - allow
        - approved
        - approve
    default: []
    label: Allowed Users
    description: "Always consent to any action from members in your allowed list."
    emoji: âœ…

blocked: 
    aliases:
        - block
    default: []
    label: Blocked Users
    description: "Ignore any roleplay command from members in your blocked list."
    emoji: ğŸš«

# keyholder: 
#     default: []
#     label: Keyholder
#     description: "Your keyholder is responsible for managing your chastity."
#     emoji: ğŸ—ï¸
# 

selective: 
    default: False
    label: Selective
    description: "Always reject roleplay commands from any user not in your allowed list."
    emoji: ğŸ›¡ï¸

public: 
    default: False
    label: Public Use Slut
    description: "Always consent to any action *from* a member (except those in your blocked list.)"
    emoji: ğŸ†“

servant: 
    default: False
    label: Servant
    description: "Always consent to any request to perform an action *on* a member (except those in your blocked list.)"
    emoji: ğŸ§¹
